/*
 * Copyright 2026 Proxar
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace ZFSourceGenerator
{
    [Generator(LanguageNames.CSharp)]
    public class EntityMethodGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            const int maxArity = 9;

            // 生成 IFactoryEntity 接口 (1-9参数)
            var interfaceList = new List<string>();
            for (int i = 1; i <= maxArity; i++)
            {
                var typeParams = string.Join(", ", Enumerable.Range(1, i).Select(x => $"TArgs{x}"));
                var methodParams = string.Join(", ", Enumerable.Range(1, i).Select(x => $"TArgs{x} args{x}"));
                var interfaceInfo = $@"
public interface IFactoryEntity<TSelf, {typeParams}>
    where TSelf : IFactoryEntity<TSelf, {typeParams}>
{{
    abstract static TSelf FractoryCreateEntity
        ({methodParams});
}}
";
                interfaceList.Add(interfaceInfo);
            }

            var factoryCode = @"// <auto-generated />
#nullable enable

namespace Proxar.Entity.Interfaces;

" + string.Join("\n\n", interfaceList);

            // 生成 EntityBase 分部类 (1-9参数) - IFactoryEntity 版本
            var methodList = new List<string>();
            for (int i = 1; i <= maxArity; i++)
            {
                var typeParams = string.Join(", ", Enumerable.Range(1, i).Select(x => $"TArgs{x}"));
                var methodParams = string.Join(", ", Enumerable.Range(1, i).Select(x => $"TArgs{x} args{x}"));
                var factoryArgs = string.Join(", ", Enumerable.Range(1, i).Select(x => $"args{x}"));
                var method = $@"
    public T AddChild<T, {typeParams}>
        ({methodParams})
        where T : EntityBase, IFactoryEntity<T, {typeParams}>
    {{
        var entity = T.FractoryCreateEntity({factoryArgs});
        this.InitChild(entity);
        AddChild(entity);
        return entity;
    }}
";
                methodList.Add(method);
            }

            // 生成 EntityBase 分部类 (1-9参数) - Func 委托版本
            var funcMethodList = new List<string>();
            var funcMethodList2 = new List<string>();
            var funcMethodList3 = new List<string>();
            var funcMethodList4 = new List<string>();
            var funcMethodList5 = new List<string>();
            for (int i = 1; i <= maxArity; i++)
            {
                var typeParams = string.Join(", ", Enumerable.Range(1, i).Select(x => $"TArgs{x}"));
                var methodParams = string.Join(", ", Enumerable.Range(1, i).Select(x => $"TArgs{x} args{x}"));
                var funcTypeParams = string.Join(", ", Enumerable.Range(1, i).Select(x => $"TArgs{x}")) + ", T";
                var factoryArgs = string.Join(", ", Enumerable.Range(1, i).Select(x => $"args{x}"));

                var method = @$"
    public T AddChild<T, {typeParams}>
        (Func<{funcTypeParams}> factory, {methodParams})
        where T : EntityBase
    {{
        var entity = factory({factoryArgs});
        this.InitChild(entity);
        AddChild(entity);
        return entity;
    }}";
                funcMethodList.Add(method);

                var method2 = @$"
    public T AddChildWithId<T, {typeParams}>(long id, {methodParams})
        where T : EntityBase, IFactoryEntity<T, {typeParams}>
    {{
        var entity = T.FractoryCreateEntity({factoryArgs});
        this.InitChild(entity, id);
        AddChild(entity);
        return entity;
    }}";

                funcMethodList2.Add(method2);

                var method3 = @$"
    public T AddChildWithId<T, {typeParams}>(long id, Func<{funcTypeParams}> factory, {methodParams})
        where T : EntityBase
    {{
        var entity = factory({factoryArgs});
        this.InitChild(entity, id);
        AddChild(entity);
        return entity;
    }}";
                funcMethodList3.Add(method3);

                var method4 = @$"
    public T AddComponent<T, {typeParams}>(Func<{funcTypeParams}> factory, {methodParams})
        where T : EntityBase
    {{
        var obj = factory({factoryArgs});
        return (this.AddComponent(obj) as T)!;
    }}";
                funcMethodList4.Add(method4);

                var method5 = @$"
    public T AddComponent<T, {typeParams}>({methodParams})
        where T : EntityBase, IFactoryEntity<T, {typeParams}>
    {{
        var obj = T.FractoryCreateEntity({factoryArgs});
        return (this.AddComponent(obj) as T)!;
    }}";
                funcMethodList5.Add(method5);
            }
            funcMethodList.AddRange(funcMethodList2);
            funcMethodList.AddRange(funcMethodList3);
            funcMethodList.AddRange(funcMethodList4);
            funcMethodList.AddRange(funcMethodList5);
            var allMethods = string.Join("\n\n", methodList.Concat(funcMethodList));
            var partCode = @$"// <auto-generated />
#nullable enable
using Proxar.Entity.Interfaces;

namespace Proxar.Entity;

public partial class EntityBase
{{
{allMethods}
}}";

            context.RegisterPostInitializationOutput(ctx =>
            {
                ctx.AddSource("EntityFactory.g.cs", SourceText.From(factoryCode, Encoding.UTF8));
                ctx.AddSource("EntityPart.g.cs", SourceText.From(partCode, Encoding.UTF8));
            });
        }
    }
}